// Generated by Wrangler by running `wrangler types`

interface Env {
    NODE_ENV: string
    OAUTH_KV: KVNamespace
    AUTH0_DOMAIN: string
    AUTH0_AUDIENCE: string
    AUTH0_SCOPE: string
    AUTH0_CLIENT_ID: string
    AUTH0_CLIENT_SECRET: string
    API_BASE_URL: string
    MCP_OBJECT: DurableObjectNamespace<import('./src/index').AuthenticatedMCP>
    AI: Ai
}

declare namespace Cloudflare {
    interface Env {
        NODE_ENV: string
        OAUTH_KV: KVNamespace
        AUTH0_DOMAIN: string
        AUTH0_AUDIENCE: string
        AUTH0_SCOPE: string
        AUTH0_CLIENT_ID: string
        AUTH0_CLIENT_SECRET: string
        API_BASE_URL: string
        MCP_OBJECT: DurableObjectNamespace<import('./src/index').AuthenticatedMCP>
        AI: Ai
    }
}
